### ISSUE TITLE
The website linkes to Drools sub-projects redirect back to the home page

### ISSUE THREAD

**Issue by mcampbell-src** [droolsjbpm/drools-website#3]
The links in the overview on the home page that point to the Drools sub-projects (Guvnor, Fusion, Expert, etc), look like they link to specific pages for those sub-projects, but clicking on them just brings the user back to the home page.

I also don't see any other place on the website (the menu, for example) to find more information about these sub-projects, so there's no way to find out more information about what each one does or when to use them.

**Comment by mbiarnes** [comment]
links were removed temporarily
